### PR TITLE
[FRE-1238, FRE-1242] fix history page stuck loading

### PR DESCRIPTION
**Pull request by codingki**

### CODE REVIEW

**Comment by ericHgorski** [comment]
Im not getting routes on this branch!
https://github.com/user-attachments/assets/2a95d2a8-c4d0-4648-85ea-5ea24208b0f7

**Comment by codingki** [comment]
huh works fine on my end @ericHgorski

**Comment by ericHgorski** [comment]
> huh works fine on my end @ericHgorski

usually I can break loop with clicking max or clearing inputs but that didnt work this time for some reason. 

also changed the `max-width` so it didnt squeeze the time since info. rest LGTM!

**Review by ericHgorski — APPROVED** [review]
LGTM

**Pull request merged**
